name: Python application

on: [pull_request]

jobs:
  build:
    name: tests-pass
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest tests
        coverage xml -o coverage/python.xml
    - name: Report python coverage
      uses: orgoro/coverage@v3
      with:
        coverageFile: coverage/python.xml
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run linting
      run: |
        pre-commit run --all-files
