name: Update Datasets

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - 13-numfocus

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update data
        run: |
          cd funderfinder/utils
          python3 list_numfocus.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update datasets
