name: Update Datasets

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update data
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd funderfinder/utils
          python3 list_numfocus.py
          python3 list_gsoc.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update datasets
